export const categorias = [
  {
    categoria: "Filmes e Desenhos",
    palavras: [
      "shrek",
      "toy story",
      "rei leão",
      "frozen",
      "moana",
      "nemo",
      "harry potter",
      "homem aranha",
      "batman",
      "barbie",
      "mulan",
      "carros",
      "divertida mente",
      "madagascar",
      "aladdin",
      "tarzan",
      "cinderela",
      "scooby doo",
      "up",
      "os incríveis",
      "monstros s.a",
      "pocahontas",
      "valente",
      "hercules",
      "hotel transilvânia",
      "kung fu panda",
      "trolls",
      "encanto",
      "zootopia",
      "detona ralph",
      "soul",
      "elementos",
      "rapunzel",
      "fada madrinha",
      "branca de neve",
      "peter pan",
      "simba",
      "buzz",
      "woody",
      "olaf",
      "jack sparrow",
    ],
  },
  {
    categoria: "Alimentos",
    palavras: [
      "arroz",
      "feijão",
      "carne",
      "frango",
      "peixe",
      "ovo",
      "leite",
      "pão",
      "manteiga",
      "queijo",
      "tomate",
      "alface",
      "cenoura",
      "batata",
      "cebola",
      "alho",
      "azeite",
      "sal",
      "açúcar",
      "pimenta",
      "maçã",
      "banana",
      "laranja",
      "uva",
      "morango",
      "melancia",
      "abacaxi",
      "manga",
      "mamão",
      "café",
      "chá",
      "suco",
      "refrigerante",
      "água",
      "chocolate",
      "biscoito",
      "bolo",
      "sorvete",
      "pizza",
      "hambúrguer",
      "sanduíche",
      "massa",
      "macarrão",
      "lasanha",
      "sopa",
      "iogurte",
      "cereal",
      "farinha",
      "milho",
      "ervilha",
      "lentilha",
      "óleo",
    ],
  },
  {
    categoria: "Esportes",
    palavras: [
      "futebol",
      "basquete",
      "vôlei",
      "tênis",
      "corrida",
      "natação",
      "ciclismo",
      "surf",
      "skate",
      "musculação",
      "ginástica",
      "luta",
      "boxe",
      "judô",
      "karatê",
      "jiu-jitsu",
      "halterofilismo",
      "atletismo",
      "esgrima",
      "golfe",
      "handebol",
      "hóquei",
      "rugby",
      "beisebol",
      "automobilismo",
      "motocross",
      "triatlo",
      "maratona",
      "paralimpíadas",
      "xadrez",
      "damas",
      "ping pong",
      "snooker",
      "arco e flecha",
      "esqui",
      "snowboard",
      "windsurf",
      "patinação",
      "parkour",
      "capoeira",
      "treinamento",
      "técnica",
      "competição",
      "time",
      "jogador",
      "campeonato",
      "torneio",
      "medalha",
      "placar",
      "árbitro",
      "goleiro",
    ],
  },
  {
    categoria: "Animais",
    palavras: [
      "cachorro",
      "gato",
      "leão",
      "tigre",
      "urso",
      "zebra",
      "elefante",
      "girafa",
      "cavalo",
      "vaca",
      "porco",
      "galinha",
      "pato",
      "ganso",
      "coelho",
      "rato",
      "camundongo",
      "hamster",
      "cervo",
      "cabra",
      "ovelha",
      "anta",
      "lobo",
      "raposa",
      "onça",
      "jacaré",
      "crocodilo",
      "tartaruga",
      "cobra",
      "sapo",
      "rã",
      "pinguim",
      "águia",
      "gavião",
      "coruja",
      "falcão",
      "papagaio",
      "canário",
      "beija-flor",
      "golfinho",
      "baleia",
      "tubarão",
      "peixe",
      "camarão",
      "polvo",
      "lagosta",
      "estrela-do-mar",
      "ouriço",
      "abelha",
      "formiga",
      "borboleta",
      "aranha",
      "escorpião",
    ],
  },
  {
    categoria: "Sentimentos",
    palavras: [
      "amor",
      "ódio",
      "alegria",
      "tristeza",
      "raiva",
      "paz",
      "ansiedade",
      "medo",
      "esperança",
      "desespero",
      "carinho",
      "compaixão",
      "culpa",
      "orgulho",
      "vergonha",
      "gratidão",
      "ciúmes",
      "inveja",
      "respeito",
      "admiração",
      "ternura",
      "confiança",
      "desconfiança",
      "alívio",
      "angústia",
      "euforia",
      "exaustão",
      "frustração",
      "felicidade",
      "melancolia",
      "prazer",
      "satisfação",
      "afeto",
      "solidão",
      "empatia",
      "apreensão",
      "desânimo",
      "vontade",
      "entusiasmo",
      "nojo",
      "surpresa",
      "culpabilidade",
      "tédio",
      "timidez",
      "irritação",
      "desprezo",
      "compaixão",
      "excitação",
      "apatia",
      "perplexidade",
      "bem-estar",
    ],
  },
];
